# here lhotse feature computation parameters
# Network config
masknet:
  in_chan: 23
  n_src: 2
  out_chan: 23
  bn_chan: 64
  hid_size: 128
  chunk_size: 20
  hop_size: 10
  n_repeats: 6
  mask_act: 'sigmoid'
  bidirectional: true
  dropout: 0
# Training config
training:
  epochs: 200
  batch_size: 4
  num_workers: 4
  half_lr: yes
  early_stop: yes
  gradient_clipping: 5
# Optim config
optim:
  optimizer: adam
  lr: 0.001
  weight_decay: !!float 1e-5
# Data config
data:
  train_dir: data/wav8k/min/tr/
  valid_dir: data/wav8k/min/cv/
  task: sep_clean
  nondefault_nsrc:
  sample_rate: 8000
  mode: min
